autoservisas/urls.py
from django.urls import path
from . import views
from .views import CustomPasswordResetView

urlpatterns = [
    path('', views.index, name='index'),
    path('statistics/', views.statistics, name='statistics'),
    path('automobiliai/', views.automobiliai, name='automobiliai'),
    path('automobiliai/<int:pk>/', views.AutomobilisDetailView.as_view(), name='automobilis-detail'),
    path('uzsakymai/', views.UzsakymaiListView.as_view(), name='uzsakymai'),
    path('uzsakymai/<int:pk>/', views.UzsakymasDetailView.as_view(), name='uzsakymas-detail'),
    path('search/', views.search, name='search'),
    path('password-reset/', views.CustomPasswordResetView.as_view(), name='password-reset'),
    path('myautomobiliai/', views.LoanedAutomobiliaiByUserListView.as_view(), name='my-borrowed'),
    path('myautomobiliai/<uuid:pk>', views.AutomobiliaiByUserDetailView.as_view(), name='my-automobiliai'),
    path('myautomobiliai/new', views.AutomobilisByUserCreateView.as_view(), name='my-borrowed-new'),
    path('myautomobiliai/<int:pk>/update', views.AutomobilisByUserUpdateView.as_view(), name='my-automobiliai-update'),
    path('myautomobiliai/<int:pk>/delete', views.AutomobilisByUserDeleteView.as_view(), name='my-automobiliai-delete'),
    path('register/', views.register, name='register'),
    path('profilis/', views.profilis, name='profilis'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', RedirectView.as_view(url='/autoservisas/', permanent=True)),
    path('autoservisas/', include('autoservisas.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

autoservisas/models.py
from PIL import Image
from django.db import models
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from datetime import date
from tinymce.models import HTMLField

class AutomobilioModelis(models.Model):
    marke = models.CharField(max_length=255)
    modelis = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.marke} {self.modelis}"

    class Meta:
        verbose_name = 'Automobilio modelis'
        verbose_name_plural = 'Automobilio modeliai'

class Automobilis(models.Model):
    STATUS_CHOICES = [
        ('available', 'Available'),
        ('unavailable', 'Unavailable'),
        ('pending', 'Pending'),
    ]

    valstybinis_numeris = models.CharField(max_length=20)
    automobilio_modelis = models.ForeignKey(AutomobilioModelis, on_delete=models.CASCADE)
    vin_kodas = models.CharField(max_length=17)
    klientas = models.CharField(max_length=255)
    cover = models.ImageField('Viršelis', upload_to='covers', null=True)
    reader = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='available')
    due_back = models.DateField(null=True, blank=True)
    description = HTMLField()


    def __str__(self):
        return self.valstybinis_numeris

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        verbose_name = 'Automobilis'
        verbose_name_plural = 'Automobiliai'

    resized_cover = models.ImageField('Viršelis (Resized)', upload_to='resized_covers', null=True, blank=True)

def save(self, *args, **kwargs):
    super().save(*args, **kwargs)

    if self.cover:
        # Open the uploaded image using Pillow
        image = Image.open(self.cover.path)

        # Resize the image while preserving the aspect ratio
        target_size = (300, 300)
        image.thumbnail(target_size)

        # Save the resized image
        resized_image_path = self.cover.path.replace('covers', 'resized_covers')
        image.save(resized_image_path)

        # Update the 'resized_cover' field with the resized image path
        self.resized_cover = self.cover.name.replace('covers', 'resized_covers')
        self.save()

class Paslauga(models.Model):
    pavadinimas = models.CharField(max_length=255)

    def __str__(self):
        return self.pavadinimas

    class Meta:
        verbose_name = 'Paslauga'
        verbose_name_plural = 'Paslaugos'


class Uzsakymas(models.Model):
    STATUS_CHOICES = (
        ('N', 'Naujas'),
        ('V', 'Vykdomas'),
        ('U', 'Užbaigtas'),
        ('A', 'Atšauktas'),
    )

    statusas = models.CharField(max_length=1, choices=STATUS_CHOICES, default='N')
    data = models.DateField(verbose_name='Data', null=True, blank=True)
    automobilis = models.ForeignKey(Automobilis, on_delete=models.CASCADE)
    suma = models.CharField(max_length=255)
    pavadinimas = models.CharField(max_length=255)
    kaina = models.IntegerField()

    def __str__(self):
        return f"{self.automobilis.klientas} - {self.automobilis.automobilio_modelis} - {self.data}"

    class Meta:
        verbose_name = 'Užsakymas'
        verbose_name_plural = 'Užsakymai'


class UzsakymoEilute(models.Model):
    paslauga = models.ForeignKey(Paslauga, on_delete=models.CASCADE)
    uzsakymas = models.ForeignKey(Uzsakymas, on_delete=models.CASCADE)
    kiekis = models.CharField(max_length=255)
    kaina = models.CharField(max_length=255)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Užsakymo eilutė'
        verbose_name_plural = 'Užsakymo eilutės'


class Password(PasswordChangeForm):
    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(user, *args, **kwargs)
        self.fields['old_password'].widget.attrs.update({'class': 'form-control', 'placeholder': "Old Password"})
        self.fields['new_password1'].widget.attrs.update({'class': 'form-control', 'placeholder': "New Password"})
        self.fields['new_password2'].widget.attrs.update({'class': 'form-control', 'placeholder': "New Password"})

    def save(self, commit=True):
        password = self.cleaned_data["new_password1"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user


class AutomobilisReview(models.Model):
    automobilis = models.ForeignKey('Automobilis', on_delete=models.SET_NULL, null=True, blank=True)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Atsiliepimas', max_length=2000)

    class Meta:
        verbose_name = "Atsiliepimas"
        verbose_name_plural = 'Atsiliepimai'
        ordering = ['-date_created']


class Profilis(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nuotrauka = models.ImageField(default='img/no-img.png', upload_to='profile_pics')


    def __str__(self):
        return f"{self.user.username} profilis"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.nuotrauka.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.nuotrauka.path)

autoservisas/forms.py
from django import forms
from .models import AutomobilisReview, User, Profilis, Automobilis

class AutomobilisReviewForm(forms.ModelForm):
    class Meta:
        model = AutomobilisReview
        fields = ('content', 'automobilis', 'reviewer',)
        widgets = {'automobilis': forms.HiddenInput(), 'reviewer': forms.HiddenInput()}

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfilisUpdateForm(forms.ModelForm):
    class Meta:
        model = Profilis
        fields = ['nuotrauka']

class DateInput(forms.DateInput):
    input_type = 'date'

class AutomobilisCreateForm(forms.ModelForm):
    class Meta:
        model = Automobilis
        fields = ['automobilio_modelis', 'due_back']
        widgets = {'reader': forms.HiddenInput(), 'due_back': DateInput()}

autoservisas/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator
from django.db.models import Q
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.forms import PasswordChangeForm
from .models import Automobilis, Uzsakymas, Paslauga
from .forms import AutomobilisReviewForm, UserUpdateForm, ProfilisUpdateForm, AutomobilisCreateForm
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.views.generic.edit import FormMixin
from django.views import generic
from django.contrib.auth.views import PasswordResetView



def index(request):
    num_autoservisai = Automobilis.objects.all().count()
    num_uzsakymai = Uzsakymas.objects.all().count()
    num_instances_available = Uzsakymas.objects.filter(statusas__exact='Available').count()
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_autoservisai': num_autoservisai,
        'num_uzsakymai': num_uzsakymai,
        'num_instances_available': num_instances_available,
        'num_visits': num_visits,
    }

    return render(request, 'index.html', context=context)


def statistics(request):
    paslaugu_kiekis = Paslauga.objects.count()
    uzsakymu_kiekis = Uzsakymas.objects.count()
    automobiliu_kiekis = Automobilis.objects.count()

    context = {
        'paslaugu_kiekis': paslaugu_kiekis,
        'uzsakymu_kiekis': uzsakymu_kiekis,
        'automobiliu_kiekis': automobiliu_kiekis
    }

    return render(request, 'statistics.html', context)

def automobiliai(request):
    automobiliai = Automobilis.objects.all()
    paginator = Paginator(automobiliai, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'automobiliai.html', {'page_obj': page_obj})

class UzsakymaiListView(ListView):
    model = Uzsakymas
    template_name = 'uzsakymai.html'
    context_object_name = 'uzsakymai'
    paginate_by = 3

    def get_queryset(self):
        return super().get_queryset().order_by('id')

class UzsakymasDetailView(DetailView):
    model = Uzsakymas
    template_name = 'uzsakymas_detail.html'
    context_object_name = 'uzsakymas'

def automobilis_detail(request, pk):
    automobilis = get_object_or_404(Automobilis, pk=pk)
    return render(request, 'automobilis_detail.html', {'automobilis': automobilis})

class AutomobilisDetailView(FormMixin, DetailView):
    model = Automobilis
    template_name = 'automobilis_detail.html'
    form_class = AutomobilisReviewForm

    def get_success_url(self):
        return reverse('automobilis-detail', kwargs={'pk': self.object.id})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.automobilis = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(AutomobilisDetailView, self).form_valid(form)


def search(request):
    query = request.GET.get('query')
    automobiliai = Automobilis.objects.filter(automobilio_modelis__marke__icontains=query)
    return render(request, 'search.html', {'automobiliai': automobiliai, 'query': query})


class LoanedAutomobiliaiByUserListView(LoginRequiredMixin, generic.ListView):
    model = Automobilis
    template_name = 'user_automobiliai.html'
    paginate_by = 3

    def get_queryset(self):
        return Automobilis.objects.filter(reader=self.request.user).order_by('due_back')


class CustomPasswordResetView(PasswordResetView):
    success_url = reverse_lazy('password_reset_done')

    def form_valid(self, form):

        reset_url = self.request.build_absolute_uri(
            reverse_lazy('password_reset_confirm', args=[form.cleaned_data['uid'], form.cleaned_data['token']])
        )

        print(f'Password reset link: {reset_url}')

        return super().form_valid(form)


@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Vartotojo vardas {username} užimtas!')
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'Vartotojas su el. paštu {email} jau užregistruotas!')
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
                    messages.info(request, f'Vartotojas {username} užregistruotas!')
                    return redirect('login')
        else:
            messages.error(request, 'Slaptažodžiai nesutampa!')
            return redirect('register')
    return render(request, 'register.html')


@login_required
def profilis(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfilisUpdateForm(request.POST, request.FILES, instance=request.user.profilis)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Profilis atnaujintas")
            return redirect('profilis')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfilisUpdateForm(instance=request.user.profilis)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'profilis.html', context)

class AutomobiliaiByUserDetailView(LoginRequiredMixin, generic.DetailView):
    model = Automobilis
    template_name = 'user_automobiliai.html'



class AutomobilisByUserCreateView(LoginRequiredMixin, CreateView):
    model = Automobilis
    fields = ['automobilio_modelis', 'due_back']
    success_url = '/autoservisas/myautomobiliai/'
    template_name = 'user_automobilis_form.html'
    form_class = AutomobilisCreateForm

    def form_valid(self, form):
        form.instance.reader = self.request.user
        return super().form_valid(form)

    # Add this method to check if the user is allowed to create a new automobilis
    def test_func(self):
        return self.request.user.is_authenticated

class AutomobilisByUserUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Automobilis
    fields = ['automobilio_modelis', 'due_back']
    success_url = "/autoservisas/myautomobiliai/"
    template_name = 'user_automobilis_form.html'

    def form_valid(self, form):
        form.instance.reader = self.request.user
        return super().form_valid(form)

    def test_func(self):
        automobilis = self.get_object()
        return self.request.user == automobilis.reader


class AutomobilisByUserDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Automobilis
    template_name = 'user_automobilis_delete.html'

    def test_func(self):
        automobilis = self.get_object()
        return self.request.user == automobilis.reader

    def get_success_url(self):
        return reverse('my-borrowed')


class AutomobilisByUserCreateView(LoginRequiredMixin, generic.CreateView):
    model = Automobilis
    form_class = AutomobilisCreateForm
    success_url = '/autoservisas/myautomobiliai/'
    template_name = 'user_automobilis_form.html'

    def form_valid(self, form):
        form.instance.reader = self.request.user
        return super().form_valid(form)

autoservisas/templates/automobiliai.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h2 xmlns="http://www.w3.org/1999/html">Automobiliai</h2>

  <ul class="car-list">
    {% for automobilis in page_obj %}
      <li>
        <div class="car-info">
          <div class="car-image">
            <a href="{% url 'automobilis-detail' automobilis.pk %}">
              {% if automobilis.resized_cover %}
                <img src="{{ automobilis.resized_cover.url }}" alt="Cover Image" width="360" height="360">
              {% else %}
                <img src="{% static 'media/img/noimg.jpg' %}" alt="No Cover Image">
              {% endif %}
            </a>
          </div>
          <div class="car-details">
            <h3><a href="{% url 'automobilis-detail' automobilis.pk %}">{{ automobilis.automobilio_modelis }}</a></h3>
            <ul>
              <li><strong>Valstybinis numeris:</strong> {{ automobilis.valstybinis_numeris }}</li>
              <li><strong>VIN kodas:</strong> {{ automobilis.vin_kodas }}</li>
              <li><strong>Savininkas:</strong> {{ automobilis.klientas }}</li>
            </ul>
          </div>
        </div>
      </li>
    {% empty %}
      <li>No cars found.</li>
    {% endfor %}
  </ul>

  <div class="pagination">
    {% if page_obj.has_previous %}
      <a href="?q={{ query }}&page={{ page_obj.previous_page_number }}" class="page-link">Atgal</a>
    {% endif %}

    <span class="current-page">{{ page_obj.number }}</span>

    {% if page_obj.has_next %}
      <a href="?q={{ query }}&page={{ page_obj.next_page_number }}" class="page-link">Pirmyn</a>
    {% endif %}
  </div>
{% endblock %}

autoservisas/templates/automobilis_detail.html
{% extends 'base.html' %}

{% block content %}
  <h2>Automobilio informacija</h2>
  <h3><p>Savininkas: {{ automobilis.klientas }}</p></h3>
  <p>Automobilio modelis: {{ automobilis.automobilio_modelis }}</p>
  <p>Valstybinis numeris: {{ automobilis.valstybinis_numeris }}</p>
  <p>VIN kodas: {{ automobilis.vin_kodas }}</p>
  <p>Aprasymas: {{ automobilis.description | safe }}</p>

      <h4>Atsiliepimai:</h4>
      {% if automobilis.automobilisreview_set.all %}
        {% for review in automobilis.automobilisreview_set.all %}
          <hr>
          <strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created }}</em>
          <p>{{ review.content }}</p>
        {% endfor %}
      {% else %}
        <p>Automobilis neturi atsiliepimų</p>
    {% endif %}
      {% if user.is_authenticated %}
      <div class="fieldWrapper">
        <hr><br/>
        <h4>Palikite atsiliepimą:</h4>
       <form action="" method="post">
        {% csrf_token %}
        {{ form.content }}<br/>
        {{ form.automobilis }}  <!-- Add this line to include the hidden input field for the automobilis -->
        {{ form.reviewer }}  <!-- Add this line to include the hidden input field for the reviewer -->
          <input type="submit" value="Išsaugoti">
      </form>
      </div>
{% endif %}

{% endblock %}

autoservisas/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Automobilių užsakymai</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

  {% load static %}
  <script src="{% static 'tinymce/js/tinymce/tinymce.min.js' %}"></script>
  <script>
      tinymce.init({
          selector: '.tinymce',
          // Add any additional TinyMCE configuration options here
      });
  </script>
  <style>
    /* Additional CSS to modify top bar layout */
    .navbar-nav.ml-auto {
        display: flex;
        flex-wrap: nowrap;
    }

    .navbar-nav.ml-auto li {
        margin-right: 10px;
    }

    .form-inline {
        display: flex;
        align-items: center;
    }

    .form-inline .form-control {
        margin-right: 5px;
    }
  </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    {% block sidebar %}
      <ul class="navbar-nav ml-auto">
        <li><a href="{% url 'index' %}">Pradžia</a></li>
        <li><a href="{% url 'statistics' %}">Statistika</a></li>
        <li><a href="{% url 'uzsakymai' %}">Užsakymai</a></li>
        <li><a href="{% url 'automobiliai' %}">Automobiliai</a></li>
        <li>
          <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
            <label for="search-input" class="mr-2">Paieška:</label>
            <input id="search-input" name="query" class="form-control" type="text" placeholder="Paieška">
          </form>
        </li>
      </ul>
    {% endblock %}
  </div>
</nav>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-10">
      {% block content %}
        <h1>Sveiki!</h1>
        <!-- Display Automobilis information -->
        <h2>Automobilio informacija</h2>
        <p>Savininkas: {{ automobilis.savininkas }}</p>
        <p>Automobilio modelis: {{ automobilis.automobilio_modelis }}</p>
        <p>Valstybinis numeris: {{ automobilis.valstybinis_numeris }}</p>
        <p>VIN kodas: {{ automobilis.vin_kodas }}</p>
      {% endblock %}
    </div>
  </div>
</div>

{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'info' %}success{% endif %}" role="alert">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

{% if user.is_authenticated %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'profilis' %}">
      <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
      </svg>
      {{ user.get_username }}
    </a>
  </li>
  <li class="nav-item"><a class="nav-link" href="{% url 'my-borrowed'%}">Mano uzsakymu sarasas</a></li>
  <li class="nav-item"><a class="nav-link" href="{% url 'my-borrowed-new'%}?next=/autoservisas">Naujas</a></li>
  <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}">Atsijungti</a></li>
{% else %}
  <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Prisijungti</a></li>
  <li class="nav-item"><a class="nav-link" href="{% url 'register'%}">Registruotis</a></li>
{% endif %}
</body>
</html>

autoservisas/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Auto salonas</h1>
  <p>Sveiki atvykę į auto servisa!</p>
  <p>Šiuo metu turime:</p>
  <ul>
    <li><strong>Automobiliu:</strong> {{ num_autoservisai }}</li>
    <li><strong>Užsakymų:</strong> {{ num_uzsakymai }}</li>
    <!-- Include other information about your models -->
  </ul>
  <p>Čia jūs lankotes {{ num_visits }}-ą kartą.</p>
{% endblock %}

autoservisas/templates/profilis.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profilis.nuotrauka.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
       <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profilio info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Atnaujinti</button>
            </div>
        </form>
    </div>
{% endblock content %}

autoservisas/templates/user_automobiliai.html
{% extends "base.html" %}

{% block content %}
    <h1>Mano paimti automobiliai</h1>

    {% if automobilis_list %}
        <ul>
            {% for automobilis in automobilis_list %}
                <li class="{% if automobilis.is_overdue %}text-danger{% endif %}">
                    <img class="rounded-circle" src="{{ automobilis.klientas.profilis.url }}">
                    <a href="{% url 'automobilis-detail' automobilis.pk %}">
                        {{ automobilis.automobilio_modelis }}
                    </a> ({{ automobilis.due_back }})
                    <br>
                    <br/>
                    <a class="btn btn-primary" href="{% url 'automobilis-detail' automobilis.pk %}" role="button">Peržiūrėti</a>
                    <li><strong>Gražinimo terminas:</strong> {{ automobilis.due_back }}</li>
                    {% if automobilis.reader == user %}
                        <div>
                            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'my-automobiliai-update' automobilis.id %}">Redaguoti</a>
                        </div>
                        <div>
                            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'my-automobiliai-delete' automobilis.id %}">Ištrinti</a>
                        </div>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Šiuo metu iš mūsų nesate paėmę automobilių.</p>
    {% endif %}
{% endblock %}

autoservisas/templates/uzsakymas_detail.html
<h1>Užsakymas: {{ uzsakymas.pavadinimas }}</h1>

<p>Data: {{ uzsakymas.data }}</p>
<p>Suma: {{ uzsakymas.suma }}</p>

<h2>Užsakymo eilutės</h2>
<ul>
  {% for eilute in uzsakymas.uzsakymoeilute_set.all %}
    <li>{{ eilute.paslauga }} - {{ eilute.kiekis }} - {{ eilute.kaina }}</li>
  {% empty %}
    <li>No order lines found.</li>
  {% endfor %}
</ul>

<a href="{% url 'uzsakymai' %}" class="btn btn-primary">Back</a>

autoservisas/templates/uzsakymas_form.html
{{ form.media }}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save">
</form>